In [1]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
#importing dataset
data=pd.read_csv('C:/Users/My PC/Downloads/glass.csv')
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
StandardScaler().fit_transform(data)

array([[-1.72397593,  0.87286765,  0.28495326, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       [-1.70778837, -0.24933347,  0.59181718, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       [-1.6916008 , -0.72131806,  0.14993314, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       ...,
       [ 1.6916008 ,  0.75404635,  1.16872135, ...,  2.95320036,
        -0.5864509 ,  2.01047778],
       [ 1.70778837, -0.61239854,  1.19327046, ...,  2.81208731,
        -0.5864509 ,  2.01047778],
       [ 1.72397593, -0.41436305,  1.00915211, ...,  3.01367739,
        -0.5864509 ,  2.01047778]])

In [4]:
X=data.drop('Type',axis=1)
Y=data.Type

In [5]:
model=svm.SVC(kernel='linear')
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)
model.fit(X_train,Y_train)              

SVC(kernel='linear')

In [6]:
model.support_vectors_

array([[7.00000e+01, 1.52300e+00, 1.33100e+01, 3.58000e+00, 8.20000e-01,
        7.19900e+01, 1.20000e-01, 1.01700e+01, 0.00000e+00, 3.00000e-02],
       [7.10000e+01, 1.51574e+00, 1.48600e+01, 3.67000e+00, 1.74000e+00,
        7.18700e+01, 1.60000e-01, 7.36000e+00, 0.00000e+00, 1.20000e-01],
       [1.44000e+02, 1.51709e+00, 1.30000e+01, 3.47000e+00, 1.79000e+00,
        7.27200e+01, 6.60000e-01, 8.18000e+00, 0.00000e+00, 0.00000e+00],
       [7.30000e+01, 1.51593e+00, 1.30900e+01, 3.59000e+00, 1.52000e+00,
        7.31000e+01, 6.70000e-01, 7.83000e+00, 0.00000e+00, 0.00000e+00],
       [1.63000e+02, 1.52211e+00, 1.41900e+01, 3.78000e+00, 9.10000e-01,
        7.13600e+01, 2.30000e-01, 9.14000e+00, 0.00000e+00, 3.70000e-01],
       [1.50000e+02, 1.51643e+00, 1.21600e+01, 3.52000e+00, 1.35000e+00,
        7.28900e+01, 5.70000e-01, 8.53000e+00, 0.00000e+00, 0.00000e+00],
       [1.65000e+02, 1.51915e+00, 1.27300e+01, 1.85000e+00, 1.86000e+00,
        7.26900e+01, 6.00000e-01, 1.00900e+01

In [7]:
model.n_support_

array([1, 3, 2, 3, 4, 3])

In [8]:
Y_pred=model.predict(X_test)

print("Accuracy\n",accuracy_score(Y_test,Y_pred))
print("\nConfusion Matrix\n",confusion_matrix(Y_test,Y_pred))
print("\nClassification Report\n",classification_report(Y_test,Y_pred))

Accuracy
 0.9846153846153847

Confusion Matrix
 [[18  0  0  0  0  0]
 [ 0 24  0  0  0  0]
 [ 0  1  5  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0 12]]

Classification Report
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       0.96      1.00      0.98        24
           3       1.00      0.83      0.91         6
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        12

    accuracy                           0.98        65
   macro avg       0.99      0.97      0.98        65
weighted avg       0.99      0.98      0.98        65



In [9]:
#different models
model1=svm.SVC(kernel='sigmoid')
model2=svm.SVC(kernel='poly')
model3=svm.SVC(kernel='rbf')

#training model
model1.fit(X_train,Y_train)
model2.fit(X_train,Y_train)
model3.fit(X_train,Y_train)

SVC()

In [10]:
#accuracy of models
Y_pred1=model1.predict(X_test)
Y_pred2=model2.predict(X_test)
Y_pred3=model3.predict(X_test)

print("Accuracy of Model1 : \n",accuracy_score(Y_pred1,Y_test))

print("\nAccuracy of Model2 : \n",accuracy_score(Y_pred2,Y_test))

print("\nAccuracy of Model3 : \n",accuracy_score(Y_pred3,Y_test))

Accuracy of Model1 : 
 0.6153846153846154

Accuracy of Model2 : 
 0.9384615384615385

Accuracy of Model3 : 
 0.8153846153846154
